services:
  - type: web
    name: akibaplus
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths: [Dockerfile]
    envVars:
      - key: APP_ENV
        value: production

